homeassistant:
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: UTC
  customize: !include customize.yaml

frontend:
config:
updater:
discovery:
history:
logbook:
map:
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

logger:
  default: info

recorder:
  db_url: !secret mariadb_url

mqtt:
  discovery: true
  broker: 192.168.1.84
  port: 1883
  username: robin
  password: !secret mqtt_password

camera:
  - platform: local_file
    file_path: /share/motion/latest.jpg
    name: "Live view"
  - platform: local_file
    file_path: /share/motion/dummy.jpg
    name: "dummy"

sensor:
  - platform: yr
  - platform: mqtt
    name: particles_03um
    state_topic: "wipy/"
    value_template: "{{ value_json.particles_03um }}"
    unit_of_measurement: 03um
  - platform: mqtt
    name: particles_05um
    state_topic: "wipy/"
    value_template: "{{ value_json.particles_05um }}"
    unit_of_measurement: 05um
  - platform: mqtt
    name: particles_10um
    state_topic: "wipy/"
    value_template: "{{ value_json.particles_10um }}"
    unit_of_measurement: 10um
  - platform: mqtt
    name: particles_25um
    state_topic: "wipy/"
    value_template: "{{ value_json.particles_25um }}"
    unit_of_measurement: 25um
  - platform: mqtt
    name: particles_50um
    state_topic: "wipy/"
    value_template: "{{ value_json.particles_50um }}"
    unit_of_measurement: 50um
  - platform: mqtt
    name: particles_100um
    state_topic: "wipy/"
    value_template: "{{ value_json.particles_100um }}"
    unit_of_measurement: 100um_foo

panel_iframe:
  ssh:
    title: SSH
    icon: mdi:wrench
    url: http://hassio.local:7681
  ide:
    title: IDE
    icon: mdi:code-braces
    url: http://hassio.local:8321
  portainer:
    title: Portainer
    icon: mdi:docker
    url: http://hassio.local:9000
  jupyter:
    title: Jupyter
    icon: mdi:code-braces
    url: http://hassio.local:7777
  bokeh:
    title: Bokeh
    icon: mdi:code-braces
    url: http://hassio.local:8123/local/barplot.html
  sqliteweb:
    title: SQLite Web
    icon: mdi:database
    url: https://hassio.local:6210
  logviewer:
    title: Log viewer
    icon: mdi:code-braces
    url: https://hassio.local:4277

zone:
  # This will override the default home zone
  - name: Home
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    elevation: 39
    unit_system: metric
    time_zone: Europe/London
    radius: 1000
