homeassistant:
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: UTC
  customize: !include customize.yaml

frontend:
config:
updater:
discovery:
history:
logbook:
map:
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

logger:
  default: info

mqtt:
  discovery: true
  broker: 192.168.1.84
  port: 1883
  username: robin
  password: !secret mqtt_password

camera:
  - platform: local_file
    file_path: /share/motion/latest.jpg
    name: "Live view"
  - platform: local_file
    file_path: /share/motion/dummy.jpg
    name: "dummy"

device_tracker:
  - platform: hue

sensor:
  - platform: yr
  - platform: hue

panel_iframe:
  ssh:
    title: SSH
    icon: mdi:wrench
    url: http://hassio.local:7681
  ide:
    title: IDE
    icon: mdi:code-braces
    url: http://hassio.local:8321
  jupyter:
    title: Jupyter
    icon: mdi:code-braces
    url: http://hassio.local:7777
  glances:
    title: Glances
    icon: mdi:speedometer
    url: http://hassio.local:61208

zone:
  # This will override the default home zone
  - name: Home
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    elevation: 39
    unit_system: metric
    time_zone: Europe/London
    radius: 1000
